name: jsoncheck

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: json-syntax-check
        uses: limitusus/json-syntax-check@v1
        with:
          pattern: "\\.json$"
      - if: success()
        name: update success status
        run : |
          gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          /repos/PokemonAutomation/ServerConfigs-PA-SHA/statuses/${{ github.sha }} \
          -f state='success' \
          -f context='json' \
        env:
          GH_TOKEN: ${{ github.token }}
      - if: failure()
        name: update failed status
        run : |
          gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          /repos/PokemonAutomation/ServerConfigs-PA-SHA/statuses/${{ github.sha }} \
          -f state='failure' \
          -f context='json' \
        env:
          GH_TOKEN: ${{ github.token }}
